### ISSUE TITLE
Apply topic(s) to improve findability?

### ISSUE THREAD

**Issue by katrinleinweber** [larsxschneider/hubsync#5]
Hi Lars!

Several similar projects as yours have set the [topic `git-sync`](https://github.com/topics/git-sync). Have you considered also [applying that topic](https://help.github.com/articles/classifying-your-repository-with-topics/)? There is also the [`repository-synchronization`](https://github.com/topics/repository-synchronization), albeit rarer.

Cheers!

**Comment by larsxschneider** [comment]
Hi Katrin! Thanks for the hint! I've added those topics 👍 😊 !

**Comment by katrinleinweber** [comment]
Cool! Thank you :-)
